---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /home/funmicra/Appdata/heimdall/config:/config
    ports:
      - 86:80
      - 8443:443
    restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
